#!/bin/bash
set -e

##
# javanile/loopdoor (v0.0.1)
##

curl -s -o /usr/local/bin/loopdoor https://javanile.github.io/loopdoor/loopdoor
curl -s -o /etc/systemd/system/loopdoor.service https://javanile.github.io/loopdoor/loopdoor.service

chmod +x /usr/local/bin/loopdoor
chmod +x /etc/systemd/system/loopdoor.service

echo "loopdoor: files downloaded."
